# main.py

from password_validation import validate_password
from exception import (
    PasswordLengthException,
    PasswordCaseException,
    PasswordDigitException,
    PasswordSpecialCharException
)

if __name__ == "__main__":
    new_password = input("Enter the new password: ")

    try:
        result_message = validate_password(new_password)
        print(result_message)
    except (PasswordLengthException, PasswordCaseException, PasswordDigitException, PasswordSpecialCharException) as e:
        print(f"Invalid password: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
